/*document.write('hello');
console.log('world');
document.write('<ul><li>Hello</li></ul>');
//document It is used to give commands within an HTML file, build codes, and modify the style.css.//
window.alert('hii');
var Mo7;
Mo7='Moayad';
Mo7=20;
document.write(Mo7);
let MJS;
MJS='Moayad';
MJS=25;
document.write(MJS);

let name='Moayad';
let age=20;
console.log(`My name is ${name} and i'm ${age} years old`)

console.log(+'10');
console.log(+'ahmad');

let m=5;
m+=+'mohamed';
console.log(typeof m);*/

console.log(Number('55'));
console.log(parseInt('5 mohammed'))
console.log(parseInt('mohammed 5'))//Error لانه مابنفع في هاذي الحالة تكون النصوص قبل الارقام
console.log(parseInt('5.2'))//حيرجع رقم صحيح مش عشري 
console.log(parseFloat('5.2'))